### ISSUE TITLE
Configuring for *very* plain tsv

### ISSUE THREAD

**Issue by bpj** [chrisbra/csv.vim#115]
How do I best configure the plugin for tab separated values where the delimiter matches `\t` and a column matches `\T\+`, i.e. any characters -- notably including `"` -- except `\t` are legal in values?
I tried with `let b:col='\T\+'` but that doesn't seem to do the trick.

**Comment by chrisbra** [comment]
it should detect tab delimited files by default, doesn't it?

**Comment by bpj** [comment]
Yes, but it seems to get confused when there are more than one ASCII double
quote within a field. I'll try to remember to post a M(N)WE later.

Den 31 aug 2017 08:43 skrev "Christian Brabandt" <notifications@github.com>:

it should detect tab delimited files by default, doesn't it?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/chrisbra/csv.vim/issues/115#issuecomment-326204970>,
or mute
the thread

**Comment by chrisbra** [comment]
try `:let g:csv_delim="\t"` or even `:let g:csv_col='[^\t]*\t'` (replace the second `\t` by an actual tab character, otherwise the regex is wrong). After setting both variables, you need to reinit the plugin using `:InitCSV`. You could also set `let g:csv_strict_columns = 1` which makes the regex to parse the csv much easier to understand.

However a minimal working example that shows the problem would be appreciated, so I can have a look.
