### ISSUE TITLE
ftplugin Function not found when using Vim 'pack/start'

### ISSUE THREAD

**Issue by jeetsukumaran** [chrisbra/csv.vim#129]
When opening a CSV/TSV file, I get:

```
Error detected while processing BufRead Auto commands for "*.csv":
E117: Unknown function: CSVArrangeCol 
```

The problem is with this line: https://github.com/chrisbra/csv.vim/blob/master/plugin/csv.vim#L15-L17 .

It looks like 'ftplugin/csv.vim' is not loaded before the 'plugin/csv.vim' executes.

I have not faced this issue before, when my plugin was located under '~/.vim/bundle' and managed by Pathogen or Vim-Plug. I am now using the native modern Vim package architecture, and the 'csv.vim' loading logic fails.

Could I suggest that you move CSVArrangeCol (and all other functions) to e.g., 'autoload/csv.vim', and call it appropriately (e.g., ``csv#CSVArrangeCol``)? This is robust and works across all versions of Vim, and will be compatible with they plugin layout of new versions of Vim going forward.

**Comment by chrisbra** [comment]
Hm, since the beginning of pack support I have been using `~/.vim/pack/minpac/start/csv.vim` and it has been working flawlessly for me.  However I am not using the automatic commands when editing csv files, so that might explain why I haven't noticed it yet. 
I'll check you PR, but won't be available for the next week, so it might take me a while until I come to that (and it probably needs some testing time).

**Comment by chrisbra** [comment]
I merged your changes. I needed to fix the `SID` thingy, but seems to work so far. Please check, if you notice any changes.
Thanks.
