### ISSUE TITLE
separator does not show correctly in quote

### ISSUE THREAD

**Issue by kkew3** [chrisbra/csv.vim#133]
When a column value is quoted, in normal mode the quoted commas are still shown as a `|`. For example, the CSV file:

```
Name,Description
enum,"one, two, and three"
```

would appear as:

```
Name|Description
enum|"one| two| and three"
```

However, it would be reasonable to expect:

```
Name|Description
enum|"one, two, and three"
```

Thank you so much for inspecting the issue!

**Comment by chrisbra** [comment]
Yeah, that is a known problem. It only happens in the last column, because no delimiter (and content) is following. 
 I have not found a good workaround for this. I tried adding `,\@=`  to the Delimiter definition, but this might then cause the last cell value to be concealed and that is certainly wrong.

**Comment by kkew3** [comment]
Thanks for your reply! Despite a bit of imperfection, this plugin does have helped me a lot. I'm closing this issue.
