### ISSUE TITLE
Movement commands J and K can move to wrong column if current cell is longer than destination cell

### ISSUE THREAD

**Issue by zestyping** [chrisbra/csv.vim#139]
### Description

When the current cell contains more characters than the cell in the same column of the preceding row, pressing `K` can move to the wrong cell in the preceding row.  Specifically, if the cursor is on character N of the current cell, then pressing `K` moves the cursor to the position N - 1 characters to the right of the start of the corresponding cell in the preceding row, ignoring cell delimiters.  If the corresponding cell in the preceding row contains fewer than N characters, this lands in the wrong cell.

Instead, the cursor should move to the last character in the corresponding cell in the preceding row.  If no other movement is performed, the cursor should also remember that its virtual position in the cell is N, so that pressing `J` immediately after `K` returns to the original position N in the original cell.

When the current cell contains more characters than the cell in the same column of the next row, pressing `J` can move to the wrong cell in the next row.  Specifically, if the cursor is on character N of the current cell, then pressing `J` moves the cursor to the position N - 1 characters to the right of the start of the corresponding cell in the next row, ignoring cell delimiters.  If the corresponding cell in the next row contains fewer than N characters, this lands in the wrong cell.

Instead, the cursor should move to the last character in the corresponding cell in the next row.  If no other movement is performed, the cursor should also remember that its virtual position in the cell is N, so that pressing `K` immediately after `J` returns to the original position N in the original cell.

### Example 1
```
a,b,c,d
efgh,ijkl
m,n,o,p
```

Actual behaviour: Place the cursor on `h`. Press `K`.  The cursor moves to the comma after `b`.  Press `J`.  The cursor moves to `j`.

Expected behaviour: Place the cursor on `h`.  Press `K`.  The cursor moves to `a`.  Press `J`. The cursor returns to `h`.

Actual behaviour: Place the cursor on `h`. Press `J`. The cursor moves to the comma after `n`. Press `K`. The cursor moves to `j`.

Expected behaviour: Place the cursor on `h`. Press `J`. The cursor moves to `m`. Press `K`. The cursor returns to `h`.

### Example 2

The virtual position should be remembered even if the cursor travels up or down multiple rows.  Pressing `J` N times followed by `K` N times should return to the original location; and pressing `K` N times followed by `J` N times should return to the original location.

Other explicit movements like `h` or `l` should cause the virtual position to be forgotten.

```
abcd,efgh
ij,kl
mn,op
qr,st
```

Expected behaviour: Place the cursor on `h`. Press `JJJKKK`. The cursor should return to `h`.

Expected behaviour: Place the cursor on `h`. Press `JhK`. The cursor should arrive at `e`.

**Comment by chrisbra** [comment]
Well, this has always been a best effort approach and worked actually only well, if the starting and destination cells had the same width. This is not the case for your example, so I fixed it to only adjust the position within the cell after moving upwards/downwards if starting and destination cells have the same width. Else it will move to the beginning of the cell.

Regarding your example 2, I don't agree with it. The wanted, virtual position is only remembered for a single movement and will be stored individually for each movement. But that means, you cannot expect it to be the same after chaining several movements together. Or saying it differently, "Why expecting the position of `JJJKKK` to be the same and not that of a say a movement, that happened several steps before that?" So that is expected.

**Comment by zestyping** [comment]
Thanks, this is much better.  I understand your opinion on Example 2, that's fine!
