### ISSUE TITLE
Enhancement: CSVDuplicate should ask if user wants to resolve/delete duplicates one by one

### ISSUE THREAD

**Issue by reportaman** [chrisbra/csv.vim#186]
[CSVDuplicate](https://github.com/chrisbra/csv.vim#check-for-duplicate-records) is yet another nifty feature... It would be nice if ``csv.vim`` could iterate the user over the list to help them resolve/delete duplicates. In the current interface "Press ENTER or type command to continue" makes the list disappear & one needs to refer it multiple times. This feature will also lift the practical limitation of matching only 10 duplicates at most, as deleting duplicates can expose more in the next run of ``CSVDuplicate``. Thanks!

Ideally all the rows that match would be in the list, not just ones that show up later as duplicates. This model assumes that csv has some from of top-bottom ordering, and entries on top are "legit" and ones matching below are "duplicates". It can be the other way round too. So an ideal way the program could iterate the user over the list would be to go over each entry that has another match. When the cursor is on a matching entry it would show other rows that match, and ask user to modify or delete the entry under the cursor.

**Comment by chrisbra** [comment]
as mentioned in the help, this is going to give you an indication, if the column list contains duplicate values. It is by no means meant to let the user edit/delete those and I don't think this is practical (and it would be a challenge to have a nice user interface, so that one knows that one is currently in `:Duplicate` mode).

Also, this runs over the complete file. As CSV files tend to be huge, I do not want it to iterate over the whole list. Also the message will be stored in the message history, so a  `:mess` will show you the output.
