### ISSUE TITLE
use the first line (header) to decide the column width

### ISSUE THREAD

**Issue by jchain** [chrisbra/csv.vim#45]
This is a feature request. 

Can we force the column widths to be the field widths in the header line?

**Comment by chrisbra** [comment]
Hi John!

On Mi, 15 Apr 2015, John Chain wrote:

> This is a feature request. 
> 
> Can we force the column widths to be the field widths in the header line?

Since :ArrangeCol usually caches the column width, you can make it work 
like this:
:1ArrangeCol!
:%ArrangeCol

The first ArrangeCol recalculates the column width ('!') attribute of 
the given row and aligns it, the seconds ArrangeCol command uses the 
cached  column width and aligns all columns to that width. 

Note, I don't know what happens, if there are fields wider than from the 
header line. You might destroy data in that case.

Best,
Christian
-- 
Es gehört zur Tugend und Lebensart, von andern nicht zu sehr sein
Recht zu fordern.
		-- Jean Paul

**Comment by chrisbra** [comment]
After a second thought, I don't think, this will work. Will think about a way to make this work.

**Comment by chrisbra** [comment]
Okay, I have just pushed an update. Use :%ArrangeCol 1 to use the width of the first row.
