### ISSUE TITLE
Header fields no longer recognized

### ISSUE THREAD

**Issue by jeetsukumaran** [chrisbra/csv.vim#79]
Given a file like:

~~~
 a, b, c
 1, 2, 3
 4, 5, 6
~~~

with '3a35bf1', the headers ("a", "b", "c") used to be recognized.

With '2f640f0', I get "CSV: Header has no field 2"

**Comment by chrisbra** [comment]
Hi Jeet!

On Mo, 29 Feb 2016, Jeet Sukumaran wrote:

> Given a file like:
> 
> ~~~
>  a, b, c
>  1, 2, 3
>  4, 5, 6
> ~~~
> 
> with '3a35bf1', the headers ("a", "b", "c") used to be recognized.
> 
> With '2f640f0', I get "CSV: Header has no field 2"

Hm, this works for me. I noticed a different problem when opening an 
empty file and adding the data, then the first and second line is 
highlighted as header. That seems to be caused by a Vim bug.
For now, I worked around that.
Can you please check, latest head fixes it for you (hopefully)?

Best,
Christian
-- 
Man idealisiert jeden, den man zum ersten Male sieht - entweder auf-
oder abwärts.
		-- Jean Paul

**Comment by jeetsukumaran** [comment]
Hi Christian,

Unfortunately, it does not. Even on an existing file such as above, ''CSV_WCol' reports '1' (i.e. the column number instead of the field name, `WhatColumn` also reports '1', and as I go across columns using `L`, `H`, I get the message "CSV: Header has no field 1/2/3".

**Comment by chrisbra** [comment]
ah okay, I think I see the problem. Please try again.

**Comment by jeetsukumaran** [comment]
It works now! Thanks!
